In [1]:
import numpy as np
from smaa.ImpactMatrix import ImpactMatrix
from smaa.Alternative import Alternative
from smaa.Criterion import Criterion

im = ImpactMatrix(np.array([Alternative("alt1")]), np.array([Criterion("cri1")]), np.array([[1]],dtype=float))

In [8]:
# im.add_alternative([8.3],"test1", 1)
im.change_alternatives_name("test1","new_test1")

In [10]:
im.get_alternatives_names()

['alt1', 'new_test1', 'test2']

In [15]:
im.add_criterion([3.0,4.5],"crit2",1)

ValueError: There is already criterion named crit2. Choose other name.

In [16]:
im.impact_matrix

array([[3. , 1. ],
       [4.5, 8. ]])

In [2]:
im.impact_matrix

array([[1.]])

In [55]:
# alts = [Alternative("alt1"), Alternative("alt2"), Alternative("alt3")]
# cris = [[Criterion("cri1")]]
from smaa import create_impact_matrix_from_csv
from smaa import no_preference, ordinal_preference
from smaa import SMAA2

im = create_impact_matrix_from_csv("data_copy.csv", "cri_info.csv")
smaa = SMAA2(im,mc_it=10000)
# print(smaa.partial_utility_matrix())

In [65]:
# smaa.alg_3(no_preference)
# ordinal_preference(2, [0,1])
smaa.compute_central_weight_vectors_and_acceptability_indices(no_preference)

(array([[0.33139546, 0.66860454],
        [0.83385318, 0.16614682],
        [0.        , 0.        ]]),
 array([[0.    , 0.3344, 0.6656],
        [0.3365, 0.3291, 0.3344],
        [0.6635, 0.3365, 0.    ]]))

In [67]:
from io import StringIO
import pandas as pd

a = StringIO(
            "A,C1,C2\n"
            "A1,0.5,15.0\n"
            "A2,0.3,16.0\n"
            "A3,0.4,14.0\n"
        )

data_read = pd.read_csv(a, index_col='A')
data_read

C1   C23
A            
A1  0.5  15.0
A2  0.3  16.0
A3  0.4  14.0